### ISSUE TITLE
Wrong indentation, code wont work

### ISSUE THREAD

**Issue by silvanarmbruster** [ManuelSch/sass-scss-converter#26]
First of all, thanks for creating this!

I just wanted to test your tool and saw that the indentation of the output is wrong when converting to sass, see the attached screenshot.

--> &.hidden should apply to lightbox-wrapper but does to lightbox.

Best,
Silvan
![Screenshot 2021-11-24 at 16 59 42](https://user-images.githubusercontent.com/44025745/143272859-e5cbb266-793a-4e75-b0af-5f66f041355e.png)

**Comment by ManuelSch** [comment]
Thanks for your report.

I'll take a look at the issue and keep you updated. In the meantime, feel free to open a pull request in case you'd like to add your own quick fix.
